### ISSUE TITLE
return lazy dask array (featur request)

### ISSUE THREAD

**Issue by pr4deepr** [lens-biophotonics/dcimg#18]
Hi
   Is it possible to add a method to return a delayed dask array?
Let me know if there is a better way. 

But this is what I was thinking:

```
import dask.array as da 
from dask import delayed 

my_file = DCIMGFile(path)

z_size = my_file.zsize
y_size = my_file.ysize
x_size = my_file.xsize

delayed_reader = delayed(my_file.frame)
lazy_arrays = [delayed_reader(f) for f in range(z_size)]
dask_arrays = [da.from_delayed(delayed_reader, shape=(y_size,x_size), dtype=my_file.dtype)
    for delayed_reader in lazy_arrays
]
# Stack into one large dask.array
stack = da.stack(dask_arrays, axis=0)
stack
```

This will return a lazy array like this:

![image](https://github.com/lens-biophotonics/dcimg/assets/13831458/984e3fb6-f02a-41f2-8bf1-bbd27a2e2226)

The advantage is now I can pass this dask array to a viewer like napari and load it on demand:
```

import napari
viewer = napari.Viewer()
viewer.add_image(stack)
```

**Comment by gmazzamuto** [comment]
Can you please try and see if the newest `dcimg.py` from the master branch works? There is a new method of `DCIMGFile` called `as_dask_array()`.
